import { useEffect, useState } from "react";
import { adminApi } from "@/utils/admin-api";
import { formatDateTime } from "@/utils/bookings";

type Log = { id: number; actor_name: string; actor_id: string; action: string; target_id: string; created_at: number; details: Record<string, unknown> };
const labels: Record<string, string> = { "tours.create": "Thêm tour", "tours.update": "Sửa tour", "esims.create": "Thêm eSIM", "esims.update": "Sửa eSIM", "articles.create": "Thêm bài viết", "articles.update": "Sửa bài viết", "banners.create": "Thêm banner", "banners.update": "Sửa banner", "users.status": "Khóa / mở khóa tài khoản", "bookings.status": "Cập nhật yêu cầu vé", "service_requests.status": "Cập nhật yêu cầu tour/eSIM", "transactions.create": "Ghi nhận giao dịch", "uploads.create": "Tải ảnh", "password.change": "Đổi mật khẩu quản trị" };
const fields: Record<string, string> = { before: "Trước thay đổi", after: "Sau thay đổi", name: "Tên nội dung", beforePublished: "Hiển thị trước đó", published: "Hiển thị sau", changedFields: "Các trường thay đổi", beforeDisabled: "Bị khóa trước đó", disabled: "Bị khóa sau", status: "Trạng thái", response: "Phản hồi", title: "Tiêu đề", image: "Ảnh", active: "Bật hiển thị", id: "Mã", sessionsRevoked: "Đã thu hồi phiên cũ", bookingId: "Mã yêu cầu vé", amount: "Số tiền (VNĐ)", reference: "Mã chứng từ", paidAt: "Thời điểm thanh toán", bytes: "Dung lượng ảnh (byte)", extension: "Định dạng ảnh", kind: "Nhóm tour", destination: "Điểm đến", duration: "Thời lượng", departure: "Khởi hành", price: "Giá", summary: "Tóm tắt", itinerary: "Lịch trình", included: "Dịch vụ bao gồm", excluded: "Dịch vụ chưa bao gồm", coverage: "Vùng phủ sóng", allowance: "Dung lượng", validity: "Thời hạn", network: "Nhà mạng", activation: "Kích hoạt", instructions: "Hướng dẫn", notes: "Lưu ý", content: "Nội dung", categoryId: "Danh mục", publishedAt: "Ngày đăng", type: "Loại nội dung" };
const statuses: Record<string, string> = { received: "Đã tiếp nhận", reviewing: "Đang xử lý", quoted: "Đã báo giá", ticketed: "Đã xuất vé", completed: "Đã hoàn tất", cancelled: "Đã hủy" };
function AuditDetails({ details }: { details: Record<string, unknown> }) {
  return <dl className="space-y-3">{Object.entries(details).map(([key, value]) => <div key={key}><dt className="font-medium text-gray-500">{fields[key] ?? key}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{value && !Array.isArray(value) && typeof value === "object" ? <div className="border-l pl-3"><AuditDetails details={value as Record<string, unknown>} /></div> : Array.isArray(value) ? value.map(item => fields[String(item)] ?? String(item)).join(", ") : value === null ? "Chưa có" : typeof value === "boolean" ? value ? "Có" : "Không" : key === "status" ? statuses[String(value)] ?? String(value) : String(value)}</dd></div>)}</dl>;
}
export default function AuditPage() {
  const [page, setPage] = useState(1), [action, setAction] = useState(""), [revision, setRevision] = useState(0);
  const [data, setData] = useState<{ logs: Log[]; total: number }>({ logs: [], total: 0 });
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); setError(""); adminApi<typeof data>(`audit?page=${page}&action=${encodeURIComponent(action)}`).then(result => { if (active) setData(result); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, action, revision]);
  return <section className="space-y-4"><p className="text-sm text-gray-500">Nhật ký bắt đầu từ bản cập nhật này. Ghi lại người thao tác, thời gian và thay đổi; không lưu mật khẩu hoặc token phiên.</p><div className="flex flex-wrap gap-3"><label className="text-sm">Loại thao tác<select className="block border rounded-xl p-3 mt-1 bg-white" value={action} onChange={e => { setAction(e.target.value); setPage(1); }}><option value="">Tất cả</option>{Object.entries(labels).map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label><button className="border rounded-xl px-4 py-3 bg-white self-end" disabled={loading} onClick={() => setRevision(value => value + 1)}>Tải lại nhật ký</button></div>
    {loading ? <p role="status">Đang tải nhật ký…</p> : error ? <p role="alert" className="text-red-600">{error}</p> : data.logs.length ? data.logs.map(log => <details key={log.id} className="bg-white border rounded-xl p-4 break-words"><summary className="cursor-pointer">{labels[log.action] ?? log.action} · {log.actor_name} · {formatDateTime(log.created_at)}</summary><div className="mt-3 space-y-2 text-sm"><p>Mã quản trị: {log.actor_id}</p><p>Đối tượng: {log.target_id}</p><div className="bg-gray-50 p-3 rounded-lg"><AuditDetails details={log.details} /></div></div></details>) : <p className="bg-white border rounded-xl p-5">Chưa có thao tác được ghi nhận.</p>}
    {data.total > 30 && <div className="flex flex-wrap gap-3 items-center"><span>Trang {page} · {data.total} thao tác</span><button className="border rounded-lg p-2" disabled={loading || page === 1} onClick={() => setPage(page - 1)}>Trước</button><button className="border rounded-lg p-2" disabled={loading || page * 30 >= data.total} onClick={() => setPage(page + 1)}>Sau</button></div>}
  </section>;
}
