import { FormEvent, useEffect, useState } from "react";
import { adminApi } from "@/utils/admin-api";
import { ServiceRequest, ServiceStatus, SERVICE_STATUS } from "@/utils/service-requests";
import ServiceRequestInfo from "@/components/service-request-info";
import { formatDateTime } from "@/utils/bookings";

type AdminRequest = ServiceRequest & { customerEmail: string };
export default function ServiceManager() {
  const [page, setPage] = useState(1), [revision, setRevision] = useState(0), [items, setItems] = useState<AdminRequest[]>([]), [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [selected, setSelected] = useState<AdminRequest | null>(null), [status, setStatus] = useState<ServiceStatus>("received"), [response, setResponse] = useState("");
  useEffect(() => { let active = true; setLoading(true); setError(""); adminApi<{ requests: AdminRequest[]; total: number }>(`service-requests?page=${page}`).then(data => { if (active) { setItems(data.requests); setTotal(data.total); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, revision]);
  async function save(event: FormEvent) { event.preventDefault(); if (!selected || busy) return; setBusy(true); setError(""); try { await adminApi("service-requests/status", { id: selected.id, status, response }); setSelected(null); setRevision(value => value + 1); } catch (e) { setError(e instanceof Error ? e.message : "Không cập nhật được yêu cầu."); } finally { setBusy(false); } }
  return <section className="space-y-4"><p className="text-sm text-gray-500">Tiếp nhận tư vấn tour/eSIM và phản hồi cho khách trong lịch sử. Trạng thái hoàn tất do nhân viên xác nhận; chưa tự đặt dịch vụ hay cấp mã eSIM.</p><button className="bg-white border rounded-xl px-4 py-3" disabled={loading || busy} onClick={() => setRevision(value => value + 1)}>Làm mới yêu cầu tour/eSIM</button>{error && <p role="alert" className="text-red-600">{error}</p>}
    {selected && <div className="bg-white border rounded-2xl p-5 space-y-4"><p className="text-sm break-all">Tài khoản: {selected.customerEmail}</p><ServiceRequestInfo item={selected} /><form onSubmit={save}><fieldset disabled={busy} className="space-y-3"><label className="block text-sm">Trạng thái<select className="block w-full border rounded-xl p-3 mt-1 bg-white" value={status} onChange={e => setStatus(e.target.value as ServiceStatus)}>{Object.entries(SERVICE_STATUS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="block text-sm">Phản hồi cho khách hàng<textarea rows={4} maxLength={5000} className="block w-full border rounded-xl p-3 mt-1" value={response} onChange={e => setResponse(e.target.value)} /></label><div className="flex gap-3"><button className="rounded-xl bg-blue-600 text-white px-4 py-3">Lưu trạng thái & phản hồi</button><button type="button" className="border rounded-xl px-4 py-3" onClick={() => setSelected(null)}>Đóng</button></div></fieldset></form></div>}
    {loading ? <p role="status">Đang tải yêu cầu…</p> : items.length ? items.map(item => <article key={item.id} className="bg-white border rounded-xl p-4 flex flex-wrap justify-between gap-3 items-center"><div className="min-w-0 break-words"><h3 className="font-semibold">{item.item.name}</h3><p className="text-sm text-gray-500">{item.request.fullName} · {item.request.phone}</p><p className="text-sm text-blue-600">{SERVICE_STATUS[item.status]} · {formatDateTime(item.createdAt)}</p></div><button className="border rounded-xl px-4 py-3" disabled={busy} onClick={() => { setSelected(item); setStatus(item.status); setResponse(item.response); }}>Xem / xử lý</button></article>) : <p className="bg-white border rounded-xl p-5">Chưa có yêu cầu tour/eSIM.</p>}
    {total > 20 && <div className="flex flex-wrap gap-3 items-center"><span>Trang {page} · {total} yêu cầu</span><button className="border rounded-lg p-2" disabled={loading || busy || page === 1} onClick={() => { setSelected(null); setPage(page - 1); }}>Trước</button><button className="border rounded-lg p-2" disabled={loading || busy || page * 20 >= total} onClick={() => { setSelected(null); setPage(page + 1); }}>Sau</button></div>}
  </section>;
}
